# =============================================================================
# Repository Module — Main definition
# =============================================================================
# Sets up the entire lifecycle of a single repo:
#   repo → branches → teams → memberships → labels → CODEOWNERS → branch protection
#
# Terraform derives the ordering between resources from its dependency graph;
# no manual order is defined here.
# =============================================================================

locals {
  # Role name → the actor form that branch protection understands.
  # Users are written as "/user", teams as "org/team-slug".
  role_actors = {
    "mentor"              = "${var.org_name}/${github_team.mentors.slug}"
    "developer"           = "${var.org_name}/${github_team.developers.slug}"
    "head-of-engineering" = "${var.org_name}/${var.org_admin_team_slug}"
  }

  # GitHub does not allow write operations on an archived repo; protection, label
  # and file synchronization are disabled in that case.
  active = !var.archived

  codeowners_content = join("\n", concat(
    [
      "# This file is generated by Terraform - do not edit by hand.",
      "# Source: config/repositories/${var.name}.yml (mentors, code_owners)",
      "",
      "# Default ownership",
      "*                       @${var.org_name}/${github_team.mentors.slug}",
    ],
    length(var.code_owners) > 0 ? ["", "# Path-specific ownership"] : [],
    [
      for path, owners in var.code_owners :
      format("%-23s %s", path, join(" ", [for o in owners : "@${o}"]))
    ],
    [""],
  ))

  # --- Template distribution -----------------------------------------------

  # The template tree mirrors the target tree exactly: the templates/CONTRIBUTING.md
  # file becomes CONTRIBUTING.md in the repo. That is why there is no separate
  # "source → target" mapping; the key is the path in both the template and the repo.
  #
  # The catalog lives here, not in config: writing file paths in config would
  # require touching config every time the template tree changes. Config only says
  # "which group, in which mode".
  templates_root = "${path.module}/../../templates"

  file_catalog = {
    "CONTRIBUTING.md"                            = "contributing"
    "SECURITY.md"                                = "security"
    ".editorconfig"                              = "editorconfig"
    ".github/PULL_REQUEST_TEMPLATE.md"           = "pr_template"
    ".github/dependabot.yml"                     = "dependabot"
    ".github/ISSUE_TEMPLATE/bug_report.yml"      = "issue_templates"
    ".github/ISSUE_TEMPLATE/feature_request.yml" = "issue_templates"
    ".github/ISSUE_TEMPLATE/config.yml"          = "issue_templates"
  }

  # Repo path → mode. Those set to "none" and archived repos are filtered out.
  managed_files = local.active ? {
    for repo_path, group in local.file_catalog :
    repo_path => lookup(var.files, group, "none")
    if lookup(var.files, group, "none") != "none"
  } : {}

  seed_paths = toset([for p, mode in local.managed_files : p if mode == "seed"])

  # Workflows are always strict — governance files (ROADMAP.md K1).
  workflow_paths = local.active ? toset([
    for name in var.workflows : ".github/workflows/${name}.yml"
  ]) : toset([])

  strict_paths = setunion(
    toset([for p, mode in local.managed_files : p if mode == "strict"]),
    local.workflow_paths,
  )
}

# --- Repo ------------------------------------------------------------------

resource "github_repository" "this" {
  name        = var.name
  description = var.description
  visibility  = var.visibility
  archived    = var.archived

  has_issues   = var.has_issues
  has_projects = var.has_projects
  has_wiki     = var.has_wiki

  # For the default branch to exist, the repo must be born with an initial commit.
  auto_init = var.auto_init

  # The merge strategy is aligned with docs/branching-strategy.md:
  # feature → develop squash, release/hotfix → main merge commit.
  allow_squash_merge     = true
  allow_merge_commit     = true
  allow_rebase_merge     = false
  delete_branch_on_merge = true

  dynamic "template" {
    for_each = var.template_repo == null ? [] : [var.template_repo]
    content {
      owner      = template.value.owner
      repository = template.value.repository
    }
  }

  # --- Security ---
  # NOTE: the `vulnerability_alerts` field is NOT here — the provider deprecated it
  # ("Use the github_repository_vulnerability_alerts resource instead"). It is defined
  # as a separate resource below.
  #
  # Secret scanning is free ONLY on public repos; a private repo requires GHAS
  # (Enterprise) and the API returns `422`. That is why the condition also includes
  # `visibility` — so a private repo with `true` in config does not blow up the apply
  # but is skipped silently.
  #
  # Silent skipping is normally a bad pattern; the reason it is acceptable here is
  # that the decision depends on the PLAN, not on config — the user is not writing
  # anything wrong, GitHub simply does not offer this feature on that repo type.
  #
  # `advanced_security` is deliberately absent: implicitly on for public, requires a
  # license for private.
  dynamic "security_and_analysis" {
    for_each = (var.secret_scanning && var.visibility == "public" && !var.archived) ? [1] : []

    content {
      secret_scanning {
        status = "enabled"
      }
      secret_scanning_push_protection {
        status = "enabled"
      }
    }
  }

  lifecycle {
    # Accidentally deleting a repo line from config must not destroy the repo.
    # If it really needs to be deleted, this block must be removed deliberately.
    # In normal use, `archived: true` is preferred over deletion.
    prevent_destroy = true
  }
}

# --- Dependabot vulnerability alerts ----------------------------------------
# The `vulnerability_alerts` field on `github_repository` was deprecated by the
# provider and will be removed in the future. This resource takes its place.
#
# When it was brought into config on 2026-08-18, it turned out to be OFF on this
# repo — the control plane itself had not been receiving vulnerability alerts for
# months. The reason: this repo was created by hand before Terraform, while the
# pilot repos were born from the module. Concrete proof that nothing set up by hand
# gets audited.
#
# Archived repos are excluded: GitHub makes an archived repo's settings read-only,
# and apply would fail.
resource "github_repository_vulnerability_alerts" "this" {
  count = local.active ? 1 : 0

  repository = github_repository.this.name
  enabled    = var.vulnerability_alerts
}

# --- Branches --------------------------------------------------------------

# auto_init creates the "main" branch; if the default branch differs, we create it separately.
resource "github_branch" "default" {
  count = var.default_branch == "main" ? 0 : 1

  repository    = github_repository.this.name
  branch        = var.default_branch
  source_branch = "main"
}

resource "github_branch_default" "this" {
  count = var.default_branch == "main" ? 0 : 1

  repository = github_repository.this.name
  branch     = github_branch.default[0].branch
}

# --- Teams -----------------------------------------------------------------
# Permission is granted to a team, not to a person. When a person leaves the
# project, a single membership is removed and all their access ends.

resource "github_team" "mentors" {
  name        = "${var.name}-mentors"
  description = "${var.name} mentors - accountable for the repository"
  privacy     = "closed"
}

resource "github_team" "developers" {
  name        = "${var.name}-devs"
  description = "${var.name} developers"
  privacy     = "closed"
}

resource "github_team" "viewers" {
  name        = "${var.name}-viewers"
  description = "${var.name} viewers - read-only access"
  privacy     = "closed"
}

# The head-of-engineering role has organization-wide scope: it holds admin
# permission on every repo. This access is also a technical necessity: GitHub only
# accepts a team into branch protection's push allow-list if the team has access to
# the repo. The collaborators resource below provides that access too (the org_admins
# team block).
data "github_team" "org_admins" {
  slug = var.org_admin_team_slug
}

# --- Access: AUTHORITATIVE collaborator set --------------------------------
# Repo access comes ONLY from teams; this resource is the SINGLE and COMPLETE
# (authoritative) source of the repo's collaborator + team list. EVERY direct user
# grant not in config (i.e. not in these teams) is REMOVED on apply — this is what
# delivers the promise "remove from config = access truly goes away". Adding a direct
# collaborator was a back door that pierced the model (see the 2026-09-09 access test);
# it was closed.
#
# ⚠️ An archived repo becomes read-only on GitHub; collaborators cannot be changed.
# That is why this is managed only on ACTIVE repos (count). An archived repo is
# already a frozen state that nobody can write to.
resource "github_repository_collaborators" "this" {
  count      = local.active ? 1 : 0
  repository = github_repository.this.name

  team {
    team_id    = github_team.mentors.slug
    permission = lookup(var.role_permissions, "mentor", "admin")
  }

  team {
    team_id    = github_team.developers.slug
    permission = lookup(var.role_permissions, "developer", "push")
  }

  team {
    team_id    = github_team.viewers.slug
    permission = lookup(var.role_permissions, "viewer", "pull")
  }

  team {
    team_id    = data.github_team.org_admins.slug
    permission = lookup(var.role_permissions, "head-of-engineering", "admin")
  }
}

resource "github_team_membership" "mentors" {
  for_each = toset(var.mentors)

  team_id  = github_team.mentors.id
  username = each.value
  role     = "maintainer"
}

resource "github_team_membership" "developers" {
  for_each = toset(var.developers)

  team_id  = github_team.developers.id
  username = each.value
  role     = "member"
}

resource "github_team_membership" "viewers" {
  for_each = toset(var.viewers)

  team_id  = github_team.viewers.id
  username = each.value
  role     = "member"
}

# --- Labels ----------------------------------------------------------------
# The plural `github_issue_labels` is used instead of the singular `github_issue_label`.
#
# Reason: when GitHub creates a new repo it also creates its own default labels
# (bug, documentation, enhancement, good first issue, help wanted, question...).
# Since the singular resource issues a "create" call for each label, it collides with
# those names and returns a 422 already_exists error. The plural resource, on the
# other hand, manages the repo's entire label set: it updates existing ones, adds
# missing ones, and deletes those not in the list. This way every repo has the same
# standard set and GitHub's default labels are cleaned up.

resource "github_issue_labels" "this" {
  count = local.active ? 1 : 0

  repository = github_repository.this.name

  dynamic "label" {
    for_each = var.labels
    content {
      name        = label.value.name
      color       = label.value.color
      description = label.value.description
    }
  }
}

# When migrating from the singular resource to the plural one, the labels created on
# the first apply are removed from state but are NOT DELETED from GitHub (destroy =
# false). Were they deleted, the plural resource would have to recreate them, causing
# an unnecessary delete-create round. The plural resource takes over the existing
# labels as they are.
removed {
  from = github_issue_label.this

  lifecycle {
    destroy = false
  }
}

# --- CODEOWNERS ------------------------------------------------------------
# The require_code_owner_review setting enforces nothing if there is no CODEOWNERS
# file in the repo. For that reason the file is generated from configuration.

resource "github_repository_file" "codeowners" {
  count = local.active && var.manage_codeowners_file ? 1 : 0

  repository          = github_repository.this.name
  branch              = var.default_branch
  file                = ".github/CODEOWNERS"
  content             = local.codeowners_content
  commit_message      = "chore(github): sync CODEOWNERS from configuration"
  overwrite_on_create = true

  depends_on = [github_branch.default]
}

# --- Template distribution -------------------------------------------------
# Two separate resources, because the `lifecycle` block CANNOT BE DYNAMIC:
# `ignore_changes` cannot come from a variable, nor be selected by mode via
# `for_each`. There is no way to make the strict/seed distinction in a single
# resource — this is a known limitation of Terraform.
#
# `file()` is used, NOT `templatefile()`. Reason: the workflow templates contain
# GitHub Actions expressions (like `${{ matrix.go-version }}`), and Terraform would
# mistake these for its own template syntax and raise a parse error. The templates
# are copied verbatim; no variables are injected.
#
# LINE-ENDING NORMALIZATION — `replace(..., "\r\n", "\n")`
# On Windows, a checkout with `core.autocrlf=true` converts the templates to CRLF;
# on Linux and macOS they stay LF. Without normalization, the content `file()` reads
# varies by platform, and **depending on who runs the apply** all strict files appear
# "changed" every time.
#
# It happened live on 2026-08-16: with only dependabot.yml edited, the plan showed
# changes in 18 files; both sides of the diff were byte-for-byte identical.
# A control plane must not produce different results depending on the machine running it.

# strict — Terraform owns the content. A manual change is reverted on the next apply.
# Governance files and all workflows go through here.
resource "github_repository_file" "strict" {
  for_each = local.strict_paths

  repository          = github_repository.this.name
  branch              = var.default_branch
  file                = each.value
  content             = replace(file("${local.templates_root}/${each.value}"), "\r\n", "\n")
  commit_message      = "chore(github): sync ${each.value} from templates"
  overwrite_on_create = true

  depends_on = [github_branch.default]
}

# seed — written only on first creation. The repo may then change the content to
# suit itself; Terraform never touches it again. For content files.
resource "github_repository_file" "seed" {
  for_each = local.seed_paths

  repository          = github_repository.this.name
  branch              = var.default_branch
  file                = each.value
  content             = replace(file("${local.templates_root}/${each.value}"), "\r\n", "\n")
  commit_message      = "chore(github): seed ${each.value} from templates"
  overwrite_on_create = true

  lifecycle {
    # The file has been handed over to the repo. Content drift does not count as drift.
    ignore_changes = [content]
  }

  depends_on = [github_branch.default]
}

# --- Branch protection -----------------------------------------------------

resource "github_branch_protection" "this" {
  for_each = local.active ? var.protected_branches : {}

  repository_id = github_repository.this.node_id
  pattern       = each.key

  # false: mentors (admin) must be able to push to a protected branch.
  enforce_admins = each.value.enforce_admins

  allows_deletions    = each.value.allow_deletions
  allows_force_pushes = each.value.allow_force_push

  require_conversation_resolution = each.value.require_conversation_resolution

  required_pull_request_reviews {
    required_approving_review_count = each.value.required_reviews
    require_code_owner_reviews      = each.value.require_code_owner_review
    dismiss_stale_reviews           = each.value.dismiss_stale_reviews
  }

  dynamic "required_status_checks" {
    for_each = length(each.value.require_status_checks) > 0 ? [1] : []
    content {
      strict   = true
      contexts = each.value.require_status_checks
    }
  }

  dynamic "restrict_pushes" {
    for_each = length(each.value.push_allowed_roles) > 0 ? [1] : []
    content {
      push_allowances = [
        for role in each.value.push_allowed_roles :
        local.role_actors[role] if contains(keys(local.role_actors), role)
      ]
    }
  }

  lifecycle {
    # Consistency lock. What produces the `ci/test` check is the aggregator job inside
    # templates/.github/workflows/ci.yml; if that workflow is not delivered to the repo,
    # the check is NEVER reported and PRs wait forever.
    #
    # This is not a theoretical warning: on 2026-08-15, after the access fix, when the
    # normal developer flow came into play, exactly this happened — even an approved PR
    # could not be merged (see docs/pilot-verification.md Section 6.4). To keep it from
    # passing silently, it errors at the plan stage.
    precondition {
      condition = (
        !contains(each.value.require_status_checks, "ci/test")
        || contains(var.workflows, "ci")
      )
      error_message = join(" ", [
        "Repo '${var.name}': branch '${each.key}' requires the 'ci/test' status check,",
        "but 'ci' is not in the workflows list - the check would never be reported and",
        "pull requests could never be merged. Either add 'ci' to the workflows list in",
        "config, or remove 'ci/test' from require_status_checks.",
      ])
    }
  }

  depends_on = [github_branch.default, github_repository_collaborators.this]
}
